<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <xs:simpleType name="UUID">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MimeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9!#$&amp;\-\^_.+]+/[a-zA-Z0-9!#$&amp;\-\^_.+]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="file">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="UUID"/>
        <xs:element name="filename_download">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="1"/>
              <xs:maxLength value="255"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="title">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="1"/>
              <xs:maxLength value="255"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="type" type="MimeType"/>
        <xs:element name="filesize">
          <xs:simpleType>
            <xs:restriction base="xs:long">
              <xs:minInclusive value="0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="width" type="xs:int" minOccurs="0"/>
        <xs:element name="height" type="xs:int" minOccurs="0"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="tags" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="uploaded_on" type="xs:dateTime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
