/* soapFileSearchService.cpp
   Generated by gSOAP 2.8.135 for backend/soap/file_search.h

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapFileSearchService.h"

FileSearchService::FileSearchService()
{	this->soap = soap_new();
	this->soap_own = true;
	FileSearchService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

FileSearchService::FileSearchService(const FileSearchService& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
}

FileSearchService::FileSearchService(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	FileSearchService_init(_soap->imode, _soap->omode);
}

FileSearchService::FileSearchService(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	FileSearchService_init(iomode, iomode);
}

FileSearchService::FileSearchService(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	FileSearchService_init(imode, omode);
}

FileSearchService::~FileSearchService()
{	if (this->soap_own)
	{	FileSearchService::destroy();
		soap_free(this->soap);
	}
}

void FileSearchService::FileSearchService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL },
        { "SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "fs", "http://localhost:8081/fs.wsdl", NULL, NULL },
        { NULL, NULL, NULL, NULL} /* end of namespaces[] */
    };
	soap_set_namespaces(this->soap, namespaces);
}

void FileSearchService::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void FileSearchService::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	FileSearchService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
FileSearchService *FileSearchService::copy()
{	FileSearchService *dup = SOAP_NEW_UNMANAGED(FileSearchService);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}
#endif

FileSearchService& FileSearchService::operator=(const FileSearchService& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
	}
	return *this;
}

int FileSearchService::soap_close_socket()
{	return soap_closesock(this->soap);
}

int FileSearchService::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

int FileSearchService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this->soap, string, detailXML);
}

int FileSearchService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

int FileSearchService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this->soap, string, detailXML);
}

int FileSearchService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

void FileSearchService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void FileSearchService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *FileSearchService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

void FileSearchService::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *FileSearchService::soap_header()
{	return this->soap->header;
}

#ifndef WITH_NOIO
int FileSearchService::run(int port, int backlog)
{	if (!soap_valid_socket(this->soap->master) && !soap_valid_socket(this->bind(NULL, port, backlog)))
		return this->soap->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->soap->errnum == 0) // timeout?
				this->soap->error = SOAP_OK;
			break;
		}
		if (this->serve())
			break;
		this->destroy();
	}
	return this->soap->error;
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int FileSearchService::ssl_run(int port, int backlog)
{	if (!soap_valid_socket(this->soap->master) && !soap_valid_socket(this->bind(NULL, port, backlog)))
		return this->soap->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->soap->errnum == 0) // timeout?
				this->soap->error = SOAP_OK;
			break;
		}
		if (this->ssl_accept() || this->serve())
			break;
		this->destroy();
	}
	return this->soap->error;
}
#endif

SOAP_SOCKET FileSearchService::bind(const char *host, int port, int backlog)
{	return soap_bind(this->soap, host, port, backlog);
}

SOAP_SOCKET FileSearchService::accept()
{	return soap_accept(this->soap);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int FileSearchService::ssl_accept()
{	return soap_ssl_accept(this->soap);
}
#endif
#endif

int FileSearchService::serve()
{
#ifndef WITH_FASTCGI
	this->soap->keep_alive = this->soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (this->soap->keep_alive > 0 && this->soap->max_keep_alive > 0)
			this->soap->keep_alive--;
#endif
		if (soap_begin_serve(this->soap))
		{	if (this->soap->error >= SOAP_STOP)
				continue;
			return this->soap->error;
		}
		if ((dispatch() || (this->soap->fserveloop && this->soap->fserveloop(this->soap))) && this->soap->error && this->soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this->soap);
#else
			return soap_send_fault(this->soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(this->soap);
		soap_end(this->soap);
	} while (1);
#else
	} while (this->soap->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_fs__searchFiles(struct soap*, FileSearchService*);
static int serve_fs__hello(struct soap*, FileSearchService*);

int FileSearchService::dispatch()
{	return dispatch(this->soap);
}

int FileSearchService::dispatch(struct soap* soap)
{
	FileSearchService_init(soap->imode, soap->omode);
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "fs:searchFiles"))
		return serve_fs__searchFiles(soap, this);
	if (!soap_match_tag(soap, soap->tag, "fs:hello"))
		return serve_fs__hello(soap, this);
	return soap->error = SOAP_NO_METHOD;
}

static int serve_fs__searchFiles(struct soap *soap, FileSearchService *service)
{	struct fs__searchFiles soap_tmp_fs__searchFiles;
	struct fs__searchFilesResponse soap_tmp_fs__searchFilesResponse;
	soap_default_fs__searchFilesResponse(soap, &soap_tmp_fs__searchFilesResponse);
	soap_default_fs__searchFiles(soap, &soap_tmp_fs__searchFiles);
	if (!soap_get_fs__searchFiles(soap, &soap_tmp_fs__searchFiles, "fs:searchFiles", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->searchFiles(soap_tmp_fs__searchFiles.term, soap_tmp_fs__searchFilesResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_fs__searchFilesResponse(soap, &soap_tmp_fs__searchFilesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_fs__searchFilesResponse(soap, &soap_tmp_fs__searchFilesResponse, "fs:searchFilesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_fs__searchFilesResponse(soap, &soap_tmp_fs__searchFilesResponse, "fs:searchFilesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_fs__hello(struct soap *soap, FileSearchService *service)
{	struct fs__hello soap_tmp_fs__hello;
	struct fs__helloResponse soap_tmp_fs__helloResponse;
	soap_default_fs__helloResponse(soap, &soap_tmp_fs__helloResponse);
	soap_default_fs__hello(soap, &soap_tmp_fs__hello);
	if (!soap_get_fs__hello(soap, &soap_tmp_fs__hello, "fs:hello", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->hello(soap_tmp_fs__helloResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_fs__helloResponse(soap, &soap_tmp_fs__helloResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_fs__helloResponse(soap, &soap_tmp_fs__helloResponse, "fs:helloResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_fs__helloResponse(soap, &soap_tmp_fs__helloResponse, "fs:helloResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
