/* soapStub.h
   Generated by gSOAP 2.8.135 for backend/soap/file_search.h

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <deque>
#include <list>
#include <vector>
#include <set>

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208135
# error "GSOAP VERSION 208135 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

class fs__FileResult;	/* backend/soap/file_search.h:9 */
struct fs__searchFilesResponse;	/* backend/soap/file_search.h:20 */
struct fs__searchFiles;	/* backend/soap/file_search.h:20 */
struct fs__helloResponse;	/* backend/soap/file_search.h:21 */
struct fs__hello;	/* backend/soap/file_search.h:21 */

/* backend/soap/file_search.h:9 */
#ifndef SOAP_TYPE_fs__FileResult
#define SOAP_TYPE_fs__FileResult (11)
/* complex XML schema type 'fs:FileResult': */
class SOAP_CMAC fs__FileResult {
      public:
        /// Required element 'id' of XML schema type 'xsd:string'
        std::string id;
        /// Required element 'filename-download' of XML schema type 'xsd:string'
        std::string filename_download;
        /// Required element 'title' of XML schema type 'xsd:string'
        std::string title;
        /// Required element 'type' of XML schema type 'xsd:string'
        std::string type;
        /// Required element 'filesize' of XML schema type 'xsd:long'
        LONG64 filesize;
        /// Required element 'description' of XML schema type 'xsd:string'
        std::string description;
        /// Required element 'uploaded-on' of XML schema type 'xsd:string'
        std::string uploaded_on;
      public:
        /// Return unique type id SOAP_TYPE_fs__FileResult
        virtual long soap_type(void) const { return SOAP_TYPE_fs__FileResult; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type fs__FileResult, default initialized and not managed by a soap context
        virtual fs__FileResult *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(fs__FileResult); }
      public:
        /// Constructor with default initializations
        fs__FileResult() : id(), filename_download(), title(), type(), filesize(), description(), uploaded_on() { }
        /// Destructor
        virtual ~fs__FileResult() { }
        /// Friend allocator used by soap_new_fs__FileResult(struct soap*, int)
        friend SOAP_FMAC1 fs__FileResult * SOAP_FMAC2 soap_instantiate_fs__FileResult(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* backend/soap/file_search.h:20 */
#ifndef SOAP_TYPE_fs__searchFilesResponse
#define SOAP_TYPE_fs__searchFilesResponse (17)
/* complex XML schema type 'fs:searchFilesResponse': */
struct SOAP_CMAC fs__searchFilesResponse {
      public:
        /** Required element 'result' of XML schema type 'fs:FileResult' */
        std::vector<fs__FileResult> result;
      public:
        /** Return unique type id SOAP_TYPE_fs__searchFilesResponse */
        long soap_type() const { return SOAP_TYPE_fs__searchFilesResponse; }
        /** Constructor with member initializations */
        fs__searchFilesResponse() : result() { }
        /** Friend allocator */
        friend SOAP_FMAC1 fs__searchFilesResponse * SOAP_FMAC2 soap_instantiate_fs__searchFilesResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* backend/soap/file_search.h:20 */
#ifndef SOAP_TYPE_fs__searchFiles
#define SOAP_TYPE_fs__searchFiles (18)
/* complex XML schema type 'fs:searchFiles': */
struct SOAP_CMAC fs__searchFiles {
      public:
        /** Required element 'term' of XML schema type 'xsd:string' */
        std::string term;
      public:
        /** Return unique type id SOAP_TYPE_fs__searchFiles */
        long soap_type() const { return SOAP_TYPE_fs__searchFiles; }
        /** Constructor with member initializations */
        fs__searchFiles() : term() { }
        /** Friend allocator */
        friend SOAP_FMAC1 fs__searchFiles * SOAP_FMAC2 soap_instantiate_fs__searchFiles(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* backend/soap/file_search.h:21 */
#ifndef SOAP_TYPE_fs__helloResponse
#define SOAP_TYPE_fs__helloResponse (21)
/* complex XML schema type 'fs:helloResponse': */
struct SOAP_CMAC fs__helloResponse {
      public:
        /** Required element 'result' of XML schema type 'xsd:string' */
        std::string result;
      public:
        /** Return unique type id SOAP_TYPE_fs__helloResponse */
        long soap_type() const { return SOAP_TYPE_fs__helloResponse; }
        /** Constructor with member initializations */
        fs__helloResponse() : result() { }
        /** Friend allocator */
        friend SOAP_FMAC1 fs__helloResponse * SOAP_FMAC2 soap_instantiate_fs__helloResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* backend/soap/file_search.h:21 */
#ifndef SOAP_TYPE_fs__hello
#define SOAP_TYPE_fs__hello (22)
/* complex XML schema type 'fs:hello': */
struct SOAP_CMAC fs__hello {
      public:
        /** Return unique type id SOAP_TYPE_fs__hello */
        long soap_type() const { return SOAP_TYPE_fs__hello; }
        /** Constructor with member initializations */
        fs__hello() { }
        /** Friend allocator */
        friend SOAP_FMAC1 fs__hello * SOAP_FMAC2 soap_instantiate_fs__hello(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* backend/soap/file_search.h:22 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (23)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* backend/soap/file_search.h:22 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* backend/soap/file_search.h:22 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (26)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* backend/soap/file_search.h:22 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (29)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* backend/soap/file_search.h:22 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (30)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* LONG64 has binding name 'LONG64' for type 'xsd:long' */
#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (13)
#endif

/* std::string has binding name 'std__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (12)
#endif

/* fs__FileResult has binding name 'fs__FileResult' for type 'fs:FileResult' */
#ifndef SOAP_TYPE_fs__FileResult
#define SOAP_TYPE_fs__FileResult (11)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (30)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (29)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (26)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (23)
#endif

/* struct fs__hello has binding name 'fs__hello' for type 'fs:hello' */
#ifndef SOAP_TYPE_fs__hello
#define SOAP_TYPE_fs__hello (22)
#endif

/* struct fs__helloResponse has binding name 'fs__helloResponse' for type 'fs:helloResponse' */
#ifndef SOAP_TYPE_fs__helloResponse
#define SOAP_TYPE_fs__helloResponse (21)
#endif

/* struct fs__searchFiles has binding name 'fs__searchFiles' for type 'fs:searchFiles' */
#ifndef SOAP_TYPE_fs__searchFiles
#define SOAP_TYPE_fs__searchFiles (18)
#endif

/* struct fs__searchFilesResponse has binding name 'fs__searchFilesResponse' for type 'fs:searchFilesResponse' */
#ifndef SOAP_TYPE_fs__searchFilesResponse
#define SOAP_TYPE_fs__searchFilesResponse (17)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (32)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (31)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (25)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/* std::vector<fs__FileResult>  has binding name 'std__vectorTemplateOffs__FileResult' for type 'fs:FileResult' */
#ifndef SOAP_TYPE_std__vectorTemplateOffs__FileResult
#define SOAP_TYPE_std__vectorTemplateOffs__FileResult (14)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
